version: '3'

services:
    my-ubuntu:
        build: .
        image: my-ubuntu:latest
        container_name: my-ubuntu
        restart: always
        ports:
            - 8080:80
        expose:
            - 80
